---
language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.090.0
  allow_failures:
    - d: dmd-nightly

script:
  - dub test :gherkin-d -b unittest-cov
  - dub test -b unittest-cov
  - ./gherkin-d/cucumber-d_gherkin-d --DRT-covopt="merge:1"

after_success:
  - bash <(curl -s https://codecov.io/bash)
